### ISSUE TITLE
Unable to mount volumes for pod logging/elasticsearch

### ISSUE THREAD

**Issue by gsaslis** [gregbkr/kubernetes-kargo-logging-monitoring#5]
Hey there, 

Thanks for putting all this together!! Was exactly what I was looking for! 

Originally, I used kubespray's (btw, you may want to "replace all" here, after the recent rename) `efk_enabled` flag, just as you suggest in section 2 in the readme. That worked fine, but: 
a. I had an issue with the `KIBANA_BASE_URL` which I probably need to raise there, 
b. they're still using the old 2.4.x versions of ES/Kibana

so, i wanted to give your `kubectl apply -f logging` approach a go, but I ran into an issue with the PVC you have there. 

Here's the error message: 
```
Unable to mount volumes for pod "elasticsearch-1832401789-f41vb_logging(5cddff81-75fa-11e7-ba5a-0019994e86b3)": timeout expired waiting for volumes to attach/mount for pod "logging"/"elasticsearch-1832401789-f41vb". list of unattached/unmounted volumes=[es-data]
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "logging"/"elasticsearch-1832401789-f41vb". list of unattached/unmounted volumes=[es-data]
```

Was I supposed to have set up some dynamic volume provisioning for this to work?

**Comment by gregbkr** [comment]
Hi @gsaslis, you welcome!
Seems like your claim for volume didn't work out.

- In file https://github.com/gregbkr/kubernetes-kargo-logging-monitoring/blob/master/logging/elasticsearch-deployment.yaml try to comment `Volume-mounts` and `volume` section, and run elasticsearch without persistence. 

- Check your volume with : `kubectl get pv` or `kubectl get pvc` and try to add it as a separated file:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pv-claim
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```
Good luck!
